-- 举报表
-- 在 Supabase SQL Editor 中运行此脚本

CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  reporter_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('post', 'comment')),
  target_id BIGINT NOT NULL,
  target_title TEXT DEFAULT '',
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
  UNIQUE(reporter_id, target_type, target_id)
);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "登录用户可举报" ON reports FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "仅管理员可查举报" ON reports FOR SELECT USING (false);
