-- 收藏表 + 评论投票表
-- 在 Supabase SQL Editor 中运行

-- 1. 收藏表
CREATE TABLE bookmarks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  UNIQUE(post_id, user_id)
);

ALTER TABLE bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "收藏_select" ON bookmarks FOR SELECT USING (true);
CREATE POLICY "收藏_insert" ON bookmarks FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "收藏_delete" ON bookmarks FOR DELETE USING (auth.uid() = user_id);

-- 2. 评论投票表（up=1 认同，up=0 反对）
CREATE TABLE comment_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  comment_id BIGINT NOT NULL REFERENCES comments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  up BOOLEAN NOT NULL,
  UNIQUE(comment_id, user_id)
);

ALTER TABLE comment_votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "投票_select" ON comment_votes FOR SELECT USING (true);
CREATE POLICY "投票_insert" ON comment_votes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "投票_delete" ON comment_votes FOR DELETE USING (auth.uid() = user_id);

-- 3. 给 posts 表加 bookmarks_count 字段（可选，用于排序）
ALTER TABLE posts ADD COLUMN IF NOT EXISTS bookmarks_count INT DEFAULT 0;
