-- 量子弦之链 · 社区数据库表
-- 在 Supabase SQL Editor 中运行此脚本

-- 1. 帖子表
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  likes_count INT DEFAULT 0
);

-- 2. 评论表
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  author_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL
);

-- 3. 点赞表（防止重复点赞）
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  UNIQUE(post_id, user_id)
);

-- 4. 启用 RLS（行级安全）
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;

-- 5. RLS 策略：帖子
CREATE POLICY "所有人可看帖子" ON posts FOR SELECT USING (true);
CREATE POLICY "登录用户可发帖" ON posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "作者可删自己的帖" ON posts FOR DELETE USING (auth.uid() = author_id);

-- 6. RLS 策略：评论
CREATE POLICY "所有人可看评论" ON comments FOR SELECT USING (true);
CREATE POLICY "登录用户可评论" ON comments FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "作者可删自己的评论" ON comments FOR DELETE USING (auth.uid() = author_id);

-- 7. RLS 策略：点赞
CREATE POLICY "所有人可查看点赞" ON likes FOR SELECT USING (true);
CREATE POLICY "登录用户可点赞/取消" ON likes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "用户可删自己的点赞" ON likes FOR DELETE USING (auth.uid() = user_id);

-- 8. 自动更新 likes_count 的函数
CREATE OR REPLACE FUNCTION update_post_likes_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE posts SET likes_count = likes_count + 1 WHERE id = NEW.post_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE posts SET likes_count = likes_count - 1 WHERE id = OLD.post_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 9. 点赞触发器
CREATE TRIGGER on_like_insert
  AFTER INSERT ON likes FOR EACH ROW
  EXECUTE FUNCTION update_post_likes_count();

CREATE TRIGGER on_like_delete
  AFTER DELETE ON likes FOR EACH ROW
  EXECUTE FUNCTION update_post_likes_count();
